name: CI

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install xdotool
        run: |
          sudo apt-get install xdotool
      - name: Run headless test
        uses: GabrielBB/xvfb-action@v1
        with:
          run: |
            bash repro.sh
